### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by kistonw** [laoliudada/OpenWRT-For-Pi#8]
docker not found

**Comment by laoliudada** [comment]
> docker not found

没有找到好的教程给你参考，你可以去b站搜索一下，https://www.bilibili.com/video/BV1sE411h7zM 

希望对你有帮助！如果还有问题，请把你的设备信息一起贴上来。

**Comment by kistonw** [comment]
大佬 我刷了买个大乱交的固件 etc init里是没有docker相关服务的 而且软件包里也没有docker ce

**Comment by laoliudada** [comment]
> 大佬 我设备是nanopi neo2 刷的是大乱交的固件 etc init里是没有docker相关服务的 etc bin里也没有docker 而且软件包里也没有docker ce

推荐烧录最近的固件吧，上面百度云里有neo2的固件。
